# Copyright 2026 Scott Gardner, ninja.ing. All rights reserved.
# Production override — joins RTM network for Caddy routing
# Usage: docker compose -f docker-compose.yml -f docker-compose.server.yml up -d

services:
  api:
    mem_limit: 3g
    environment:
      - JWT_SECRET=${JWT_SECRET:?Set JWT_SECRET in .env}
      - API_KEY=${API_KEY:?Set API_KEY in .env}
      - CORS_ALLOW_ORIGINS=https://ninja.ing
      - DEFAULT_MODEL=depth-anything-v2
    ports: !reset []
    networks:
      - default
      - rtm

networks:
  default:
  rtm:
    external: true
    name: rapid-threat-modeler_default
